### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by skelleher** [JasonMillward/Autorippr#109]
New install on Windows, cannot find any discs.  
Manually running MakeMKV works fine.

The first problem is a hard-coded search for "/dev" in find_disc, which fails on Windows:

                if "/dev/" in line:
.
You might try something like:
        for line in lines:
            if line[:4] == "DRV:":
                fields = line.split(",")
                device = fields[4]
                if "/dev/" in line or device != "":
                    ...

The second problem is a hard-coded tmp path "/tmp/makemkvMessages" (/tmp doesn't exist on Windows by default).  

If I fix these two issues, it works well.  Thanks for the great tool!

----

C:\Autorippr>python autorippr.py --all --debug
2015-12-05 15:52:35 - Rip - DEBUG - Ripping initialised
2015-12-05 15:52:35 - Rip - DEBUG - Checking for DVDs
2015-12-05 15:52:49 - Rip - DEBUG - 0 DVD(s) found
2015-12-05 15:52:49 - Rip - INFO - Could not find any DVDs in drive list
2015-12-05 15:52:49 - Compress - DEBUG - Compressing initialised
2015-12-05 15:52:49 - Compress - DEBUG - Looking for videos to compress
2015-12-05 15:52:49 - Compress - INFO - Queue does not exist or is empty
2015-12-05 15:52:49 - Extras - INFO - No videos ready for filebot

C:\Autorippr>makemkvcon -r info disc:-1
MSG:1005,0,1,"MakeMKV v1.9.7 win(x86-release) started","%1 started","MakeMKV v1.9.7 win(x86-release)"
DRV:0,2,999,1,"BD-RE HL-DT-ST BD-RE  WH16NS40 1.00","A_NEW_HOPE","D:"
DRV:1,256,999,0,"","",""
DRV:2,256,999,0,"","",""
DRV:3,256,999,0,"","",""
DRV:4,256,999,0,"","",""
DRV:5,256,999,0,"","",""
DRV:6,256,999,0,"","",""
DRV:7,256,999,0,"","",""
DRV:8,256,999,0,"","",""
DRV:9,256,999,0,"","",""
DRV:10,256,999,0,"","",""
DRV:11,256,999,0,"","",""
DRV:12,256,999,0,"","",""
DRV:13,256,999,0,"","",""
DRV:14,256,999,0,"","",""
DRV:15,256,999,0,"","",""
MSG:5010,0,0,"Failed to open disc","Failed to open disc"
TCOUNT:0

Windows 8.1 64-bit
Python 2.7.10
MakeMKV 1,9,7 Beta 64-bit
HandbrakeCLI 0.10.12

**Comment by JasonMillward** [comment]
Thanks for this, I'll make these changes shortly (or accept a pull request). 

Autorippr wasn't originally designed to run on Windows so it's totally lacking in some areas.
