### ISSUE TITLE
OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by nickrupert7** [JasonMillward/Autorippr#113]
I am running Ubuntu Server through VirtualBox on my MacBook Pro, and I have just installed Autorippr per the instructions given. The test sequence runs fine and gives all "OK"s except for ffmpeg, which is optional anyways. However, when I try to run rip or all, I keep getting the following output:

```
Traceback (most recent call last)
   File "autorippr.py", line 335, in <module>
      rip(config)
   File "autorippr.py", line 127, in rip
      dvds = mkv_api.find_disc()
   File "home/nick/Autorippr/classes/makemkv.py", line 206, in find_disc
      stdout=subprocess.PIPE
   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
      errread, err write)
   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
      raise child_exception
OSError: [Errno 20] Not a directory
```

I know the basics, but I'm not terribly familiar with Linux command line, and I have no Python experience. I tried resolving the issue as some other articles describe relating to django, but no dice.

If it helps, I think it might have something to do with my settings.cfg file, because when I remove the trailing slash on the makemkvconPath, the error appears at the same place, except then, it says `OSError: [Errno 2] No such file or directory`

Thanks in advance!

Update: Just to make sure, I completely reinstalled everything, following all of the right tutorials to the letter, but the issue persists

**Comment by JasonMillward** [comment]
Would you mind sharing your `settings.cfg` file?

**Comment by nickrupert7** [comment]
Leaving makemkvconPath seems to work! I can't be sure, because it's still running, but it no longer fails immediately with the error I described.

Just for the heck of it, here's my settings.cfg file (note that I only added the .txt extension so I could attach the file here - it is just settings.cfg in the Autorippr folder)

[settings.cfg.txt](https://github.com/JasonMillward/Autorippr/files/306057/settings.cfg.txt)

**Comment by JasonMillward** [comment]
Hey that's good news.

For future reference `/usr/bin/` is the _path_ to the `makemkvcon` executable that the settings file is asking for.

**Comment by nickrupert7** [comment]
Ah! Silly me! I understand now

As for the process - the old error seems to be solved. Now I have a new one... It appears to be specific to the DVD I'm ripping, and also a problem with MakeMKV itself and not Autorippr. Still, perhaps you know of an option to tack on when the script is run, or how one of the scripts themselves might need to be edited.

The error reads:
```
Makemkv - ERROR - CellWalk algorithm failed (structure protection is too tough?), trying CellTrim algorithm
Rip - INFO - MakeMKV did not complete successfully
Rip - INFO - See log for more details
Compress - INFO - Queue does not exist or is empty
Extras - INFO - No movies ready for filbert
```

Is there a way to get past this error, or is it simply a limitation of MakeMKV's un-encryption abilities?

**Comment by JasonMillward** [comment]
Unfortunately I am unable to assist with that particular issue, you will have to seek assistance on the [makeMKV forum](http://www.makemkv.com/forum2/).

**Comment by nickrupert7** [comment]
Will do. 
Thank you so much for your help! I was getting ready to rip my hair out, but now that it's working (at least your end of things), it's going to be awesome!
