### ISSUE TITLE
How to Rip Lossless and Enable filebot renaming?

### ISSUE THREAD

**Issue by RandomNinjaAtk** [JasonMillward/Autorippr#116]
According to the help file, I should be able to run this command:

python autorippr.py --rip --extra --debug

When I execute this command it fails, it just outputs the help file information. I know you can use the "-all" option, but I do not want to compress my files, I want full lossless mkv's but the file naming is critical.

Any ideas?

I'm running the latest version, this command "python autorippr.py --rip --debug" worked, but it seems like filebot did not kick-in as it should...

**Comment by JasonMillward** [comment]
Filebot was designed to run after the compression stage. It's possible to create a `--skip-compress` arg that fires off something like: 
```
    dbvideos = database.next_video_to_compress()
    for dbvideo in dbvideos:
        if comp.check_exists(dbvideo) is not False:
            database.update_video(dbvideo, 5)
```

I will happily accept a pull request, or if you're happy to wait I can implement it in a bit.

**Comment by RandomNinjaAtk** [comment]
Thanks, I'll wait for you to update since this is not my strong point. I submitted a pull request for an almost automated install script for Ubuntu. You could put that script on your site for easier installations... I have to test my script further though.

**Comment by JasonMillward** [comment]
Should be working now if you pull from master or the latest tag

**Comment by RandomNinjaAtk** [comment]
Thanks! I'll be trying this later this week!

**Comment by tomatpasser** [comment]
When I try to run
`python autorippr.py --rip --skip-compress --extra` 
I get the usage help. How is it supposed to be used? I want to rip lossless and rename like @RandomNinjaAtk

**Comment by JasonMillward** [comment]
What version of autoripper are you running? @tomatpasser

**Comment by tomatpasser** [comment]
v1.7.0

Den 23/11/2016 04.37 skrev "Jason" <notifications@github.com>:
