### ISSUE TITLE
cant make the script download/install the new makemkv 

### ISSUE THREAD

**Issue by phn2** [JasonMillward/Autorippr#121]
Ive changed the script, as below, but when running the script it still tries and fails at downloading v. 1.10.**1**:

#Install MakeMKV
wget http://www.makemkv.com/download/makemkv-bin-1.10.2.tar.gz
wget http://www.makemkv.com/download/makemkv-oss-1.10.2.tar.gz
tar -zxmf makemkv-oss-1.10.2.tar.gz
tar -zxmf makemkv-bin-1.10.2.tar.gz
cd makemkv-oss-1.10.2
./configure
make
sudo make install
cd ..
cd makemkv-bin-1.10.2
make
sudo make install

**Comment by JasonMillward** [comment]
Updated to v1.10.2
