### ISSUE TITLE
Ripping not working error "File "autorippr.py", line 416, in <module>"

### ISSUE THREAD

**Issue by sam9s** [JasonMillward/Autorippr#123]
HI ,

I have followed the guide exactly the way on http://docs.jcode.me/autorippr/install/, everything installed good. I just skipped handbreak coz I dont want to compress the rip.

WhenI run python autorippr.py --rip ripping DOES NOT start and I get the below error

Traceback (most recent call last):
  File "autorippr.py", line 416, in <module>
    rip(config)
  File "autorippr.py", line 133, in rip
    dvds = mkv_api.find_disc()
  File "/home/sam9s/Autorippr/classes/makemkv.py", line 225, in find_disc
    stdout=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Please assist me. 
Regards
Sammy

**Comment by JasonMillward** [comment]
> OSError: [Errno 2] No such file or directory

Double check your paths in `settings.cfg`, or more specifically `makemkvconPath` . It requires a trailing slash to a custom path, or leave it as an empty string. 

If everything is okay, try running `which makemkvcon` in a terminal and paste the output here.

**Comment by sam9s** [comment]
OK thanks, Was not expecting a response, but really appreciate the help. Leaving it empty did the trick and ripping happened as intended. BUT the Audio is only DTS or DD, I would like to have the uncompressed original Audio DTS MA or DD THD, is it possible. This would make the product just unbeatable ... :)

Also any possibility of being able to Rip Audio CDs and copy to a Music Folder. 

Regards
Sammy

**Comment by JasonMillward** [comment]
I don't have any plans to build an audio cd ripping tool.

I'm having a look at audio options as well for #122

**Comment by sam9s** [comment]
Ok fair enough, that link you shared, says he is getting 5.1 audio even if the disc has 7.1, not sure if he is getting HD AUdio (DTS MA and DD THD) . I am more interested to get uncompressed audio MA and THD, please if that is something you can assist, (take yourtime) this would be a killer product for everyone

Regards
Sammy

**Comment by JasonMillward** [comment]
Closing and combining with #122
