### ISSUE TITLE
Some movies burn and Skip Around

### ISSUE THREAD

**Issue by mprobasco** [JasonMillward/Autorippr#131]
This is probably not fixable by AutoRippr... but Ill try. 
Some movies that are ripped will rip "fine" but when watched will randomly skip around in the movie. Entire sections will be missing. Or a screen will appear that says this movie has been ripped and you only get audio.. the screen never goes away.

**Comment by JasonMillward** [comment]
This is an issue with MakeMKV not Autorippr itself. Unfortunately I can't do anything about it from my end.
