### ISSUE TITLE
TV Show Support

### ISSUE THREAD

**Issue by lesgrossman** [JasonMillward/Autorippr#15]
This is a feature request if anything.  be nice to update the rip.py to 
support TV Shows.   where the output is X number of files based on 
how many episodes are on the disc

**Comment by JasonMillward** [comment]
I finally got around to it!  [Pre-release 1.7](https://github.com/JasonMillward/Autorippr/releases/tag/v1.7-test1) allows for TV shows to be ripped. 

Being a pre-release issues should be expected, don't forget to report any problems encountered.

**Comment by lesgrossman** [comment]
First bug... maybe?


Traceback (most recent call last):
  File "./autorippr.py", line 355, in <module>
    rip(config)
  File "./autorippr.py", line 125, in rip
    mkv_api = makemkv.MakeMKV(config)
  File "/home/choman/Autorippr/classes/makemkv.py", line 31, in __init__
    self.makemkvconPath = config['makemkv']['makemkvconPath']
KeyError: 'makemkvconPath'

**Comment by JasonMillward** [comment]
You'll need to update your settings file. [There's been a few changes](https://github.com/JasonMillward/Autorippr/blob/master/settings.example.cfg).

**Comment by JasonMillward** [comment]
Going to close this issues since TV show support has been implemented in the pre-releases. 

If there are any issues with those releases it would be best to raise a new issue instead of using this one.

**Comment by lesgrossman** [comment]
Looking forward to trying it out



On Mon, Nov 16, 2015 at 12:26 AM, Jason <notifications@github.com> wrote:

> e are any issues with those releases it would be best to raise a new issue
> instead of using this one.




Together We Win!   Looking for cloud storage, try copy.com
<https://copy.com?r=6BuEoY> (20g free <https://copy.com?r=6BuEoY>)
--
Chad - Sisel Promoter
Take Your Life Back! <http://choman.mysiselpro.com/>
Creating A More Meaningful Life

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows
