### ISSUE TITLE
1.7-test2 crashes on multiple titles

### ISSUE THREAD

**Issue by mikenick42** [JasonMillward/Autorippr#80]
Trying to rip Futurama S1D1.

~/makemkv/Autorippr$ python autorippr.py --rip
Traceback (most recent call last):
  File "autorippr.py", line 357, in <module>
    rip(config)
  File "autorippr.py", line 160, in rip
    forceDisableFB
  File "~/makemkv/Autorippr/classes/database.py", line 145, in insert_movie
    lastupdated=datetime.now()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4001, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4148, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2858, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3073, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3065, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: table movies has no column named multititle

**Comment by JasonMillward** [comment]
The database field `multititle` was added in 1.7-test2. You will need to delete the old `autorippr.sqlite` file in order for it to be re-created with the update schema.

**Comment by mikenick42** [comment]
Thanks for the quick response.
I have a couple more questions, if you don't mind.
Does --extra only work with single file rips? I like to rip everything
uncompressed, but when I do autorippr.py --rip --extra I just get a usage
message and nothing happens. If I use --extra without --rip it tells me
that there are no files in the filebot list. I commented out the --compress
if statement and now --all will run, but I still get a message about no
files in the filebot list.
Also, how does autorippr handle nested audio streams? I don't remember the
exact naming convention from the MakeMKV gui, but I've seen instances where
there will be a DolbyTrueHD or something like that, and then within that
stream there is a 5.1 surround or similar substream.

Thanks,
Mike

**Comment by JasonMillward** [comment]
> Does --extra only work with single file rips?

Yes. See: https://github.com/JasonMillward/Autorippr/blob/master/autorippr.py#L150
Handling multiple files (TV shows) in filebot is a little tricky, so until I or someone else figures out how to manage it correctly it is disabled when it detects multiple output files. 

> Also, how does autorippr handle nested audio streams?

MakeMKV seems to keep everything on the disc and handbrake will try to keep all audio and subtitle tracks it comes across.

**Comment by mikenick42** [comment]
Cool, thanks.
I've done a bit with using the tvdb api to rename files with python, so I
would offer to help, but I've never seen anything that breaks shows down on
a per DVD level.

Thanks,
Mike
