### ISSUE TITLE
Retaining the surround 5.1 audio?

### ISSUE THREAD

**Issue by rdlugosz** [JasonMillward/Autorippr#84]
I'm new to the world of ripping my BD collection to my nas, so thanks for a really helpful tool! After my first rip (The Aviator), I noticed that the audio was saved as 2 channel mp3, instead of the dolby digital 5.1 that exists on the blu ray.

Did I do something wrong or is it not possible to retain the bd audio in the rips?

Config is stock from the example.

**Comment by ascendedguard** [comment]
You'll need to modify your handbrake arguments in your `settings.cfg`. Here's an example of my settings for a 720p movie with 5.1 surround sound:

    # The HandBrake command line options and arguments
    # Configure this to change output quality
    # each line should start with -
    com:
        -   --x264-preset="slow"
        -   --two-pass
        -   --turbo
        -   -q 22
        -   --markers
        -   --x264-tune="film"
        -   --encoder="x264"
        -   --width 1280
        -   --height 720
        -   -x level=4.1
        -   -B 384
        -   -E fdk_aac
        -   -6 5point1

**Comment by rdlugosz** [comment]
Ah - Thanks. I since discovered https://trac.handbrake.fr/wiki/CLIGuide and was a bit blown away by the number of available options... this is a very helpful starting point!

**Comment by JasonMillward** [comment]
Just wanted to say thanks @ascendedguard, you've jumped in a few times to help people out while I've been sleeping and it's very appreciated.
